config/routes.rb
RubyChina::Application.routes.draw do
  resources :sites

  resources :posts do
    collection do
      match "tag/:tag_name" => "posts#tag_index", :via => :get, :as => :tagged
    end
  end

  resources :gikis, :path => "wiki" do 
    member do 
      get :history
    end
    
    collection do 
      get :list
      post :preview
    end
  end
  
  resources :comments
  resources :notes
  root :to => "home#index"  
 

  devise_for :users, :path => "account", :controllers => { 
      :registrations => :account,
      :omniauth_callbacks => "users/omniauth_callbacks" 
    }
  
  match "account/auth/:provider/unbind", :to => "users#auth_unbind"
  
  match "users/location/:id", :to => "users#location", :as => :location_users
  resources :users do
    member do 
      get :replies
      get :likes
      get :notes
    end 
  end
  resources :notifications, :only => [:index, :destroy] do
    collection do
      put :mark_all_as_read
    end
  end
  
  resources :nodes
  
  match "topics/node:id" => "topics#node", :as => :node_topics
  match "topics/node:id/feed" => "topics#node_feed", :as => :feed_node_topics
  match "topics/last" => "topics#recent", :as => :recent_topics
  resources :topics do
    member do
      post :reply
    end
    collection do
      get :search
      get :feed
      post :preview
    end
    resources :replies
  end

  resources :photos do
    collection do
      get :tiny_new
    end
  end
  resources :likes

  match "/search" => "search#index", :as => :search
  match "/search/topics" => "search#topics", :as => :search_topics
  match "/search/wiki" => "search#wiki", :as => :search_wiki

  namespace :cpanel do 
    root :to => "home#index"
    resources :site_configs
    resources :replies
    resources :topics do
      member do
        post :suggest
        post :unsuggest
        post :undestroy
      end
    end
    resources :nodes
    resources :sections
    resources :users do
      member do
        post :block
        post :unblock
        post :restore # from deleted state
      end
    end
    resources :photos
    resources :posts
    resources :comments
    resources :site_nodes
    resources :sites
  end  
  
  if Rails.env.development?
    mount UserMailer::Preview => 'mails/user'
  end
end

app/controllers/search_controller.rb
# coding: utf-8
class SearchController < ApplicationController
  
  before_filter :validate_search_key
   def index
     if @query_string.present?
       search = Ransack::Search.new(Topic, @search_criteria)
       @topics = search.result(:distinct => true).paginate(:page => params[:page], :per_page => 20)
     end

     @current = ["/search/topics?q=#{@query_string}"]
     
     render :action => "topics"
     
     set_seo_meta("#{t("common.search")}: #{@query_string}")
     drop_breadcrumb("#{t("common.search")}: #{@query_string}")
  end

  def topics
    
    if @query_string.present?
      search = Ransack::Search.new(Topic, @search_criteria)
      @topics = search.result(:distinct => true).paginate(:page => params[:page], :per_page => 20)
    end
    
    set_seo_meta("#{t("common.search")}: #{@query_string}")
    drop_breadcrumb("#{t("common.search")}: #{@query_string}")

   end

  def wiki
    if @query_string.present?
      @results = Wiki.search(@query_string)
    end
    
    set_seo_meta("#{t("common.search")}: #{@query_string}")
    drop_breadcrumb("#{t("common.search")}: #{@query_string}")
  end

  protected

    def validate_search_key
      @query_string = params[:q].gsub(/\\|\'|-|\/|\.|\?/, "") if params[:q].present?
      @search_criteria = {
        :title_or_body_cont => @query_string
      }
    end
end

app/helpers/search_helper.rb
module SearchHelper
  def search_result_highlight(hit, key)
    raw hit.highlights(key).collect { |t| t.format { |t1| content_tag(:span, t1, :class => "highlight") } }.join("")
  end
end

app/views/search/_base.html.erb
<% content_for :styles do %>
  <%= stylesheet_link_tag "search" %>
<% end %>

app/views/search/_menu.html.erb
<%= render_list :class => "tabs" do |li|
   li << link_to(t("menu.topics"), search_topics_path(:q => @query_string))
   li << link_to(t("menu.wiki"), search_wiki_path(:q => @query_string))
end %>

app/views/search/_no_result.html.erb
<div class="tab-pane active" id="<%= div_id %>">
    <div class="header">
      <h2></h2>
      <p class="info">
        
      </p>
    </div>
    <div class="summary">
      <blockquote>
        無搜尋結果，要不要試試 搜尋 <%= title %> 中有關 <%= link_to(" #{@query_string}", "/search/#{search_type}?q=#{@query_string}")%> 的結果？
      </blockquote>
    </div>
</div>

app/views/search/_page.html.erb
<div class="page">
  <div class="title"><%= link_to(highlight(page.title, @keywords), page_path(page.slug)) %></div>
  <div class="url"><%= link_to(page_url(page.slug), page_path(page.slug)) %></div>
  <div class="info"><%= t("common.published_at")%> <%= timeago(page.updated_at) %></div>
  <div class="summary">
    <%= highlight(truncate(page.body, :length => 300),@keywords) %>
  </div>
</div>

app/views/search/_pages_pane.html.erb
<div class="tab-pane active" id="results">
  <% results.each do |result| %>
    <div class="page">
      <div class="title"><%= link_to(result.name, giki_path(result.name)) %></div>
      <div class="summary">
        <%= truncate(result.raw_data, :length => 300) %>
      </div>
    </div>
  <% end %>
 
</div>


<script type="text/javascript">
  $(".tab-content").highlight("<%= @query_string %>");
</script>

app/views/search/_topic.html.erb
<div class="topic">
  <div class="title"><%= link_to(highlight(topic.title, @keywords), topic_path(topic)) %></div>
  <div class="url"><%= link_to(topic_url(topic), topic_path(topic)) %></div>
  <div class="info"><%= t("common.by") %> <%= user_name_tag(topic.user) %> <%= t("common.published_at")%> <%= timeago(topic.created_at) %> <%= t("common.reply_count")%>: <%= topic.replies_count %></div>
  <div class="summary">
    <%= highlight(truncate(topic.body, :length => 300),@keywords) %>
  </div>
</div>

app/views/search/_topics_pane.html.erb
<div class="tab-pane active" id="topics">
  <% topics.each do |topic| %>
    <div class="topic">
      <div class="title"><%= link_to(topic.title, topic_path(topic)) %></div>
      <div class="info">由 <%= user_name_tag(topic.user) %> <%= t("common.published_at")%> <%= timeago(topic.created_at) %></div>
      <div class="summary">
        <%= truncate(topic.body, :length => 300) %>
      </div>
    </div>
  <% end %>
</div>

app/views/search/index.html.erb
<%= render "base" %>

<div class="box">
  <%= render "menu" %>
  <div class="tab-content">
    <div class="tab-pane active" id="topics">
    <% unless @search.results.blank? %>
      <% @search.each_hit_with_result do |hit, result| %>
        <%= render "topic", :topic => result, :hit => hit %>
      <% end %>
    <% else %>
      <div class="topic">
        <%= t("common.no_search_result") %>
      </div>
    <% end %>
    </div>
    <%= will_paginate @search.results %>
  </div>
</div>

app/views/search/topics.html.erb
<%= render "base" %>

<div class="box">
  <%= render "menu" %>
  <div class="tab-content">
    <% unless @topics.blank? %>
      <%= render :partial => "topics_pane", :locals => { :topics => @topics} %>
    <% else %>
      <%= render :partial => "no_result", :locals => { :title => "Wiki", :div_id => "topics", :q => @query_string, :search_type => "wiki" }%>
    <% end %>
  </div>
</div>

app/views/search/wiki.html.erb
<%= render "base" %>

<div class="box">
  <%= render "menu" %>
  <div class="tab-content">
      <% unless @results.blank? %>
          <%= render :partial => "pages_pane", :locals => { :results => @results } %>
      <% else %>
          <%= render :partial => "no_result", :locals => { :title => "社區", :div_id => "wiki", :q => @query_string , :search_type => "topics"}%>
      <% end %>
  </div>
</div>