config/routes.rb
RubyChina::Application.routes.draw do
  resources :sites

  resources :posts do
    collection do
      match "tag/:tag_name" => "posts#tag_index", :via => :get, :as => :tagged
    end
  end

  resources :gikis, :path => "wiki" do 
    member do 
      get :history
    end
    
    collection do 
      get :list
      post :preview
    end
  end
  
  resources :comments
  resources :notes
  root :to => "home#index"  
 

  devise_for :users, :path => "account", :controllers => { 
      :registrations => :account,
      :omniauth_callbacks => "users/omniauth_callbacks" 
    }
  
  match "account/auth/:provider/unbind", :to => "users#auth_unbind"
  
  match "users/location/:id", :to => "users#location", :as => :location_users
  resources :users do
    member do 
      get :replies
      get :likes
      get :notes
    end 
  end
  resources :notifications, :only => [:index, :destroy] do
    collection do
      put :mark_all_as_read
    end
  end
  
  resources :nodes
  
  match "topics/node:id" => "topics#node", :as => :node_topics
  match "topics/node:id/feed" => "topics#node_feed", :as => :feed_node_topics
  match "topics/last" => "topics#recent", :as => :recent_topics
  resources :topics do
    member do
      post :reply
    end
    collection do
      get :search
      get :feed
      post :preview
    end
    resources :replies
  end

  resources :photos do
    collection do
      get :tiny_new
    end
  end
  resources :likes

  match "/search" => "search#index", :as => :search
  match "/search/topics" => "search#topics", :as => :search_topics
  match "/search/wiki" => "search#wiki", :as => :search_wiki

  namespace :cpanel do 
    root :to => "home#index"
    resources :site_configs
    resources :replies
    resources :topics do
      member do
        post :suggest
        post :unsuggest
        post :undestroy
      end
    end
    resources :nodes
    resources :sections
    resources :users do
      member do
        post :block
        post :unblock
        post :restore # from deleted state
      end
    end
    resources :photos
    resources :posts
    resources :comments
    resources :site_nodes
    resources :sites
  end  
  
  if Rails.env.development?
    mount UserMailer::Preview => 'mails/user'
  end
end

app/models/notification/base.rb
class Notification::Base < ActiveRecord::Base

  self.table_name = "notifications"

  scope :recent, order("id DESC")
  scope :unread, where(:is_read => false)

  # source could be reply, topic or something else
  belongs_to :source, :polymorphic => true

  belongs_to :user

  def self.for_user(user)
    where(:user => user)
  end

  def anchor
    "notification-#{id}"
  end

  def self.mark_all_as_read!
    update_all(:is_read => true)
  end
end

# == Schema Information
#
# Table name: notifications
#
#  id          :integer(4)      not null, primary key
#  type        :string(255)     not null
#  source_id   :integer(4)
#  source_type :string(255)
#  user_id     :integer(4)
#  is_read     :boolean(1)      default(FALSE)
#  created_at  :datetime        not null
#  updated_at  :datetime        not null
#

app/models/notification/general.rb
class Notification::General < Notification::Base
end

# == Schema Information
#
# Table name: notifications
#
#  id          :integer(4)      not null, primary key
#  type        :string(255)     not null
#  source_id   :integer(4)
#  source_type :string(255)
#  user_id     :integer(4)
#  is_read     :boolean(1)      default(FALSE)
#  created_at  :datetime        not null
#  updated_at  :datetime        not null
#

app/models/notification/mention.rb
class Notification::Mention < Notification::Base
end

# == Schema Information
#
# Table name: notifications
#
#  id          :integer(4)      not null, primary key
#  type        :string(255)     not null
#  source_id   :integer(4)
#  source_type :string(255)
#  user_id     :integer(4)
#  is_read     :boolean(1)      default(FALSE)
#  created_at  :datetime        not null
#  updated_at  :datetime        not null
#

app/controllers/notifications_controller.rb
# coding: utf-8
class NotificationsController < ApplicationController
  before_filter :require_user
  respond_to :html, :js, :only => [:destroy, :mark_all_as_read]

  def index
    @notifications = current_user.notifications.recent.paginate( :page => params[:page], :per_page => 20)
    current_user.read_notifications(@notifications)
    set_seo_meta("提醒")
  end

  def destroy
    @notification = current_user.notifications.find params[:id]
    @notification.destroy
    respond_with do |format|
      format.html { redirect_referrer_or_default notifications_path }
      format.js { render :layout => false }
    end
  end

  def mark_all_as_read
    current_user.notifications.unread.update_all(:is_read => true)
    respond_with do |format|
      format.html { redirect_referrer_or_default notifications_path }
      format.js { render :layout => false }
    end
  end
end

app/views/notifications/destroy.js.erb
$('#' + '<%= @notification.anchor %>').fadeOut('normal', function(){
  $(this).remove();
});

app/views/notifications/index.html.erb
<%= content_for :styles do %>
  <%= stylesheet_link_tag "notifications" %>
<% end %>
<%= content_for :scripts do %>
  <%= javascript_include_tag "notifications" %>
<% end %>

<div class="sidebar">
  <div class="box">
    <div class="content">
      <%= link_to t("common.mark_all_as_read"), mark_all_as_read_notifications_path, :class => 'btn', :method => :put, :remote => true, :disable_with => '标记所有为已读...' %>
    </div>
  </div>
</div>

<div class="content">
  <div id="notifications" class="box">
    <h1>提醒</h1>
    <table>
      <tbody>
        <% @notifications.each do |notification| -%>
          <tr id="<%= notification.anchor %>">
            <%= render :partial => "notifications/#{notification.class.name.underscore}", :locals => {:notification => notification} %>
            <td class="last">
              <%= link_to t("common.delete"), notification_path(notification), :method => :delete, :remote => true, :class => 'label delete' %>
            </td>
          </tr>
        <% end -%>
      </tbody>
    </table>
    <%= will_paginate @notifications %>
  </div>
</div>

app/views/notifications/mark_all_as_read.js.erb
$('.topbar .notifications').removeClass('unread').find('.count').text('0');
$('#notifications span.new').fadeOut('fast', function(){
  $(this).remove();
});